manager/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('', views.managerIndex, name="manager-home"),

    #users
    path('useroverview/', views.userOverview, name="manager-userOverview"),
    path('usersearch/', views.userSearch, name="manager-userSearch"),
    path('usercreate/', views.userCreate, name="manager-userCreate"),
    #USER UPDATE ROUTES
    path('user/update', views.userSearchUpdate, name="manager-userSearchUpdate"),
    path('user/suspend', views.userSuspendToogle, name="manager-userSuspendToogle"),
    path('user/sendNotificaiton', views.userSendNotification, name="manager-userSendNotification"),

    #services
    path('serviceoverview/', views.serviceOverview, name="manager-serviceOverview"),
    path('servicecreate/', views.serviceCreate, name="manager-serviceCreate"),
    path('serviceEdit/', views.serviceEdit, name="manager-serviceEdit"),
    path('serviceEditUpdate/', views.serviceEditUpdate, name="manager-serviceEditUpdate"),

    #contact overview
    path('contact/overview/', views.contactOverview, name="manager-contactOverview"),

    #news
    path('news/overview/', views.newsOverview, name="manager-newsOverview"),
    path('news/create/', views.newsCreate, name="manager-newsCreate"),
    path('news/edit/', views.newsEdit, name="manager-newsEdit"),
    path('news/editUpdate/', views.newsEditUpdate, name="manager-newsEditUpdate"),

    #testimonal 
    path('testimonal/overview/', views.testimonialPicOverview, name="manager-testimonalOverview"),
    path('testimonal/create/', views.createTestimonialPic, name="manager-testimonialCreate"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mbs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),

    #manger routes
    path('mmanager/appointment/', include('appointment.urls')),
    path('mmanager/credit/', include('credit.urls')),
    path('mmanager/voucher/', include('voucher.urls')),
    path('mmanager/notification/', include('notification.urls')),
    path('mmanager/POS/', include('pos.urls')),
    path('mmanager/employee/', include('employee.urls')),
    path('mmanager/feedback/', include('feedback.urls')),
    path('mmanager/', include('manager.urls')),
    path('verification/', include('verify_email.urls')),	
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as BaseUserManager
from PIL import Image
from django.utils import timezone, dateformat

class UserManager(BaseUserManager):
    """ User Manager that knows how to create users via email instead of username """
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

class userInfo(AbstractUser):
    object = UserManager()
    CUSTOMER = 1
    EMPLOYEE = 2
    ASSISTANT = 3
    MANAGER = 4

    ROLE_CHOICES = {
        (CUSTOMER, 'Customer'),
        (EMPLOYEE, 'Employee'),
        (ASSISTANT, 'Assistant'),
        (MANAGER, 'Manager')
    }

    username = None
    email = models.EmailField("email address", blank=False, null=False, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    role = models.PositiveBigIntegerField(choices=ROLE_CHOICES, blank=False, null=False, default="1")
    dob = models.DateField(blank=False, null=False)
    phone = models.CharField(max_length=8, unique=True)
    is_suspend = models.BooleanField(default=0)

    def __str__(self):
        return f'{self.email}'

class profile_pic(models.Model):
    user=models.OneToOneField(userInfo, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.email} profile pic'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 500 or img.width > 500:
            output_size = (500,500)
            img.thumbnail(output_size)
            img.save(self.image.path)

class contact(models.Model):
    name = models.CharField(max_length=250 ,blank=False, null=False)
    cemail = models.EmailField(blank=False, null=False)
    cphone = models.CharField(max_length=8)
    message = models.TextField(blank=False, null=False)
    is_ack = models.BooleanField(default=0)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        datevalue = dateformat.format(self.created_at, 'd b Y')
        return f'{self.name} message at {datevalue}'

manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
import datetime
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
#models
from base.models import userInfo
from .models import services, news, testimonial_pic

class userCreationFormA(UserCreationForm):
    email = forms.EmailField(required=True)
    dob = forms.DateField(required=True, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    phone = forms.CharField(required=True, max_length=8, min_length=8, validators=[RegexValidator(r'^\d{1,10}$')])
    role = forms.ChoiceField(choices=userInfo.ROLE_CHOICES)

    def clean_check_renewal_date(self):
        data = self.cleaned_data['dob']

        #check if data is !> today
        if data >= datetime.date.today():
            raise ValidationError(_('Invalid Date of Birth'))

        return data
        
    class Meta:
        model = userInfo
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name', 'dob', 'phone', 'role']

class userSuspend(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = userInfo
        fields = ['email']

class serviceform(forms.ModelForm):
    class Meta: 
        model = services
        fields = ["service_name", "service_description", "service_tnc", "service_price", "department"]

class newform(forms.ModelForm):
    class Meta:
        model = news
        fields = ["news_title", "news_description"]

class testimonialPic(forms.ModelForm):
    class Meta:
        model = testimonial_pic
        fields = ["image", "name"]

manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from django.conf import settings
from django.core.paginator import Paginator
import datetime
from decimal import Decimal

#models
from notification.models import notification, ack_notification
from base.models import userInfo, contact
from .models import services, news, testimonial_pic
from appointment.models import appointment, appointment_service
from pos.models import sales_services, sales_transaction


#forms
from notification.forms import sendNotification
from base.forms import UpdateAccountInfo, UpdateProfilePic
from django.contrib import messages
from .forms import serviceform, newform, testimonialPic


from .forms import userCreationFormA, userSuspend

#user passes test for def not class
def manager_role_check(user):
    return user.role == userInfo.MANAGER

# Create your views here.

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def managerIndex(request):
    #get only upcoming appointments
    upcominga = appointment.objects.filter(status=1).all().order_by("-created_at")[0:9]
    upcomingcount = appointment.objects.filter(status=1).all().order_by("-created_at")
    #get sales 
    todaySales = sales_transaction.objects.filter(created_at__icontains=datetime.date.today()).all()
    latestSales = sales_transaction.objects.filter(created_at__icontains=datetime.date.today()).all().order_by("-created_at")[0:6]

    #upcoming display follow html table sequence
    upcomingTable = list()
    if upcominga:
        for ua in upcominga:
            templist = list()
            templist.append(ua.id)
            tempUsername = ua.user.first_name + " " + ua.user.last_name
            templist.append(tempUsername)
            tempEmployeeName = ua.employee.user.first_name + " " + ua.employee.user.last_name
            templist.append(tempEmployeeName)
            #get service
            resultService = ua.appointment_service_set.all()
            resultService = resultService[0].service.all()
            templist.append(resultService[0].service_name)
            templist.append(str(ua.appt_date.strftime("%Y-%m-%d / %H:%M")))
            templist.append("Upcoming")
            upcomingTable.append(templist)

    #calculate the total sales for today
    totalCurrentSales = 0.00
    if todaySales:
        for ts in todaySales:
            totalCurrentSales += float(ts.grand_total)

    context ={
        "upcomingTable" : upcomingTable,
        "upcomingcount" : upcomingcount,
        "totalCurrentSales" : totalCurrentSales,
        "latestSales" : latestSales,
    }
    return render(request, 'manager/mindex.html', context=context)

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def userOverview(request):
    if request.method == "POST":
        try:
            user = userInfo.objects.get(email=request.POST["Email"])
            if not user.is_suspend:
                user.is_suspend = 1
                user.save()
                messages.success(request, f'User suspended')
            else:
                user.is_suspend = 0
                user.save()
                messages.success(request, f'User un-suspended')
            return redirect('manager-userOverview')
        except:
            messages.danger(request, f'Error in updating user')
            return redirect('manager-userOverview')

    allUsers = userInfo.objects.all().order_by("-date_joined")
    activeUsers = userInfo.objects.filter(is_active=1, is_suspend=0).all()
    suspendedUsers = userInfo.objects.filter(is_suspend=1).all()
    unverifiedEmailUsers = userInfo.objects.filter(is_active=0).all()

    #paginator
    paginator = Paginator(allUsers, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    #context 
    context = {
        "activeUsers" : activeUsers.count(),
        "suspendedUsers" : suspendedUsers.count(),
        "unverifiedEmailUsers" : unverifiedEmailUsers.count(),
        "totalUsers" : allUsers.count(),
        "users" : page_obj,
        "userSuspendForm" : userSuspend,
    }

    return render(request, 'manager/userOverview.html', context=context)

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def userCreate(request):
    if request.method == "POST":
        try:
            form = userCreationFormA(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, f'User created.')
                return redirect('manager-userOverview')
            else:
                messages.warning(request, f'Error in creating user, please try again.')
                return redirect('manager-userOverview')
        except:
            messages.warning(request, f'Error in creating user, please try again.')
            return redirect('manager-userOverview')
    else:
        context = {
            "form" : userCreationFormA(),
            
        }
    return render(request, 'manager/userCreate.html', context=context)

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def userSearch(request):
    if request.method == "POST":
        try:
            searchUser = userInfo.objects.get(phone=request.POST["phone"])
            if searchUser:                
                data = {
                    'email' : searchUser.email,
                    'first_name' : searchUser.first_name,
                    'last_name' : searchUser.last_name,
                    'phone': searchUser.phone,
                    'dob' : searchUser.dob,                    
                }
               
                UpdateProfilePicForm = UpdateProfilePic()
                UpdateAccountInfoForm = UpdateAccountInfo(initial=data)	
                sendNotificationForm = sendNotification()
                
                #get all upcoming appointments for the user
                upcomingapp = ""
                upcomingapp = appointment.objects.filter(user=searchUser, status="UPCOMING").all().order_by("-created_at")
                context = {
                    "UpdateProfilePicForm" : UpdateProfilePicForm,
                    "UpdateAccountInfoForm" : UpdateAccountInfoForm,
                    "searchUser" : searchUser,
                    "sendNotificationForm" : sendNotificationForm,
                    'vouchers' : searchUser.voucher_set.all(),
                    "upcomingapp" : upcomingapp,
                }
                messages.success(request, f'User found.')
                return render(request, 'manager/userSearch.html', context=context)
        except:
            messages.warning(request, f'No user found.')
            redirect('manager-userSearch')

    return render(request, 'manager/userSearch.html')

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def userSearchUpdate(request):
    try:
        if request.method == "POST":
            phonen = request.POST['phonen']
            ui = userInfo.objects.filter(phone=phonen).get()

            UpdateProfilePicForm = UpdateProfilePic(request.POST, request.FILES, instance=ui.profile_pic)
            UpdateAccountInfoForm = UpdateAccountInfo(request.POST, instance=ui)    

            if UpdateProfilePicForm.is_valid() and 	UpdateAccountInfoForm.is_valid():  
                UpdateProfilePicForm.save()                
                UpdateAccountInfoForm.save()
                messages.success(request, f'Your information has been updated.')
                return redirect("manager-userSearch")
    except:
        messages.warning(request, f'Eror in updating user profile. Please try again.')
        return redirect('manager-userOverview')

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def userSuspendToogle(request):
    if request.method == "POST":
        try:
            u = userInfo.objects.get(email=request.POST['email'])
            if not u.is_suspend:
                u.is_suspend = 1
                u.save()
                messages.success(request, f'User status updated.')
                redirect('manager-userOverview')
            else:
                u.is_suspend = 0
                u.save()
                messages.success(request, f'User status updated.')
                redirect('manager-userOverview')
        except:
            messages.warning(request, f'Fail to update user status.')
            redirect('manager-userOverview')
    return redirect('manager-userOverview')

@login_required
@user_passes_test(manager_role_check, login_url='/login/')
def userSendNotification(request):  
    try:  
        if request.method == "POST":
            sendNotificationForm = sendNotification(request.POST)
            if sendNotificationForm.is_valid():
                try:
                    u = userInfo.objects.get(email=request.POST['email'])                
                    if u:                    
                        sendNotificationForm.save()                    
                        ack_notification.objects.create(sent_user=u, sent_notification=sendNotificationForm.instance)
                        #send email to notify user
                        instanceNotification = sendNotificationForm.instance
                        send_mail(subject=instanceNotification.notification_title, message=instanceNotification.notification_description, from_email=settings.EMAIL_HOST_USER, recipient_list=[u.email])
                        
                        messages.success(request, f'Notification sent to user.')
                        return redirect('manager-userOverview')
                except:
                    messages.warning(request, f'Unable to send user notification.')
                    return redirect('manager-userOverview')
        
    except:
        messages.warning(request, f'Unable to send user notification.')

manager/templates/manager/contactOverview.html
{% extends 'manager/mindex.html' %}
{% load static %}

{% block content %}
<!--breadcrumb-->
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-5">
    <div class="breadcrumb-title pe-3">Contact</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="{% url 'manager-home' %}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Overview</li>
            </ol>
        </nav>
    </div>
    
</div>
<!--end breadcrumb-->

{% if contacts %}
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Message</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            {% for cs in contacts %}
                <tr>
                    <td>
                        {{cs.name}}
                    </td>
                    <td>
                        {{cs.cemail}}
                    </td>
                    <td>
                        {{cs.cphone}}
                    </td>
                    <td>{{cs.message}}</td>
                    <td>
                        {{ch.created_at|date:"F d, Y"}}
                    </td>
                    <td>
                        <form action="" method="POST">
                            {%csrf_token%}
                            <input type="text" name="csid" id="csid" value="{{cs.id}}" readonly hidden>
                            <button type="submit" class="btn btn-sm btn-primary">Acknowledge</button>
                        </form>
                    </td>
                </tr>
            {%endfor%}
        
        
        </tbody>
    </table>

    <div class="pagination mt-3">
        <span class="step-links">
            {% if contacts.has_previous %}
                <a class="btn btn-sm btn-primary" href="?page=1">&laquo; first</a>
                <a class="btn btn-sm btn-primary" href="?page={{ contacts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
            </span>

            {% if contacts.has_next %}
                <a class="btn btn-sm btn-primary" href="?page={{ contacts.next_page_number }}">next</a>
                <a class="btn btn-sm btn-primary" href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{%else%}

<div>
    <h5>No contacts..</h5>
</div>

{% endif %}

{% endblock %}

manager/templates/manager/createTestimonialPic.html
{% extends 'manager/mindex.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--breadcrumb-->
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-5">
    <div class="breadcrumb-title pe-3">Contact</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="{% url 'manager-home' %}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Overview</li>
            </ol>
        </nav>
    </div>
    
</div>
<!--end breadcrumb-->

<div>
    <form action="" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <label for="">Image resolution: 1200 by 900</label>
        {{form|crispy}}
        <button type="submit" class="btn btn-primary col-12">Create testimonal</button>
    </form>

</div>

{%endblock%}

manager/templates/manager/serviceCreate.html
{% extends 'manager/mindex.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--breadcrumb-->
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-5">
    <div class="breadcrumb-title pe-3">Service</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="{% url 'manager-home' %}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Create</li>
            </ol>
        </nav>
    </div>
    
</div>
<!--end breadcrumb-->

<div>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary col-12">Create Service</button>
    </form>
</div>

{% endblock %}

manager/templates/manager/userOverview.html
{% extends 'manager/mindex.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--breadcrumb-->
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-5">
    <div class="breadcrumb-title pe-3">User</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="{% url 'manager-home' %}"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Overview</li>
            </ol>
        </nav>
    </div>
    
</div>
<!--end breadcrumb-->

<div class="row row-cols-1 row-cols-md-2 row-cols-xl-4">
    <div class="col">
        <div class="card radius-10 bg-primary bg-gradient">
            <div class="card-body">
                <div class="d-flex align-items-center">
                    <div>
                        <p class="mb-0 text-white">Active users</p>
                        {% if activeUsers %}
                            <h4 class="my-1 text-white">{{activeUsers}}</h4>
                        {% else %}
                            <h4 class="my-1 text-white">0</h4>
                        {% endif %}
                    </div>
                    <div class="text-white ms-auto font-35"><i class='bx bx-user-pin'></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card radius-10 bg-danger bg-gradient">
            <div class="card-body">
                <div class="d-flex align-items-center">
                    <div>
                        <p class="mb-0 text-white">Suspended users</p>
                        {% if suspendedUsers %}
                            <h4 class="my-1 text-white">{{suspendedUsers}}</h4>
                        {% else %}
                            <h4 class="my-1 text-white">0</h4>
                        {% endif %}
                    </div>
                    <div class="text-white ms-auto font-35"><i class='bx bx-user-pin'></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card radius-10 bg-warning bg-gradient">
            <div class="card-body">
                <div class="d-flex align-items-center">
                    <div>
                        <p class="mb-0 text-dark">Email unverified users</p>
                        {% if unverifiedEmailUsers %}
                            <h4 class="my-1 text-white">{{unverifiedEmailUsers}}</h4>
                        {% else %}
                            <h4 class="my-1 text-white">0</h4>
                        {% endif %}
                    </div>
                    <div class="text-dark ms-auto font-35"><i class='bx bx-user-pin'></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card radius-10 bg-success bg-gradient">
            <div class="card-body">
                <div class="d-flex align-items-center">
                    <div>
                        <p class="mb-0 text-white">Total users</p>
                        {% if totalUsers %}
                            <h4 class="my-1 text-white">{{totalUsers}}</h4>
                        {% else %}
                            <h4 class="my-1 text-white">0</h4>
                        {% endif %}
                    </div>
                    <div class="text-white ms-auto font-35"><i class='bx bx-user-pin'></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

<div class="card radius-10">
    <div class="card-header bg-transparent">
        <h6 class="mb-0 font-weight-bold">New users</h6>
    </div>
    <div class="table-responsive p-3">
        <table class="table mb-0">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Credit</th>
                    <th>Email verification</th>
                    <th>Status</th>
                    <th>Role</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% if users %}
                    {% for user in users%}
                        <tr>
                            <td>{{user.email}}</td>
                            <td>{{user.first_name}} {{user.last_name}}</td>
                            <td>{{user.phone}}</td>
                            <td>                               
                                {{user.credits.balance}}                               
                            </td>
                            <td>{{user.is_active}}</td>
                            <td>
                                {% if not user.is_suspend %}
                                    Active
                                {% else %}
                                    Suspended
                                {% endif %}
                            </td>
                            <td>{{user.get_role_display}}</td>
                            <td>
                                {% if not user.is_suspend %}
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#suspend{{user.id}}">
                                        Suspend
                                    </button>
                                {% else %}
                                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#suspend{{user.id}}">
                                        Activate
                                    </button>
                                {% endif %}
                                    
                                    <!-- Modal -->
                                    <div class="modal fade" id="suspend{{user.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="suspend" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="suspend">Suspend user</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <form action="" method="POST">
                                                    {% csrf_token %}
                                                    <div class="modal-body">                                                         
                                                            <input type="email" id="id_email" name="{{userSuspendForm.email.label}}" value="{{user.email}}" readonly hidden> 
                                                            {% if not user.is_suspend %}                                                                   
                                                                <p>Confirm suspend {{user.email}}?</p>
                                                            {% else %}                                                                
                                                                <p>Confirm un-suspend {{user.email}}?</p>
                                                            {% endif %}
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>                                                              
                                
                            </td>
                        </tr>
                    {%endfor%}
                {% endif %}

                
            </tbody>
        </table>
        <div class="pagination mt-3">
            <span class="step-links">
                {% if users.has_previous %}
                    <a class="btn btn-sm btn-primary" href="?page=1">&laquo; first</a>
                    <a class="btn btn-sm btn-primary" href="?page={{ users.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ users.number }} of {{ users.paginator.num_pages }}.
                </span>
        
                {% if users.has_next %}
                    <a class="btn btn-sm btn-primary" href="?page={{ users.next_page_number }}">next</a>
                    <a class="btn btn-sm btn-primary" href="?page={{ users.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>


    </div>
</div>


{% endblock %}